// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/devstudio-cinematic/Cinematic.tsx": () => import("../components/mockups/devstudio-cinematic/Cinematic.tsx"),
  "./components/mockups/devstudio-editorial/Editorial.tsx": () => import("../components/mockups/devstudio-editorial/Editorial.tsx")
};
